### ISSUE TITLE
Invalid API

### ISSUE THREAD

**Issue by rockypabalate** [fazleo/Recipe-Generator-Using-Gemini-Pro-Vision#1]
![Screenshot (239)](https://github.com/fazleo/Recipe-Generator-Using-Gemini-Pro-Vision/assets/125625074/175cdb0d-ea8d-4fb2-8e53-5003fb6a8ccd)
Invalid API why... Hope will notice this issues

InvalidArgument: 400 API key not valid. Please pass a valid API key. [reason: "API_KEY_INVALID" domain: "googleapis.com" metadata { key: "service" value: "generativelanguage.googleapis.com" } ]

**Comment by fazleo** [comment]
You can see a ".env" named file in repository.

![Screenshot from 2024-03-22 20-28-25](https://github.com/fazleo/Recipe-Generator-Using-Gemini-Pro-Vision/assets/75975431/e1417241-e9e1-4ee0-a01b-3faf5c74e910)


Here, you need to replace with your Gemini API Key within the double quotes, You can generate from link: https://ai.google.dev/ ,using your google account.

Then run the code with provided instruction.

Note:
Removed my API-key on purpose to prevent unwanted usage.

**Comment by rockypabalate** [comment]
> You can see a ".env" named file in repository.
> 
> ![Screenshot from 2024-03-22 20-28-25](https://private-user-images.githubusercontent.com/75975431/316068489-e1417241-e9e1-4ee0-a01b-3faf5c74e910.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNDM2NzgsIm5iZiI6MTcxMTE0MzM3OCwicGF0aCI6Ii83NTk3NTQzMS8zMTYwNjg0ODktZTE0MTcyNDEtZTllMS00ZWUwLWEwMWItM2ZhZjVjNzRlOTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDIxMzYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNTMzYWRjOWMxMDUyNDBlYzkxZGRlYjk3MTI4OWIwYjg0YjhkYmRlNWU2ZWFjN2I5MzFkYmZjYzVlODkyMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yXyA-qDJYEBIOYbu8v1vxc4HZV1HMdpytsMCUlBpXUg)
> 
> Here, you need to replace with your Gemini API Key within the double quotes, You can generate from link: https://ai.google.dev/ ,using your google account.
> 
> Then run the code with provided instruction.
> 
> Note: Removed my API-key on purpose to prevent unwanted usage.

**Comment by rockypabalate** [comment]
It Works.
Thanks
